spring:
  datasource:
    url: jdbc:mysql://meat-partners-db-dev.czrwc1deke4a.ap-northeast-2.rds.amazonaws.com:3306/MT_SERVICE?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mary
    password: wjdeowkd!@34
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-tms-dev
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 0
      maximum-pool-size: 5

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        storage_engine: innodb
    hibernate:
      ddl-auto: validate
    database: mysql

  mvc:
    static-path-pattern: /static/**

logging:
  config: classpath:logback.xml
  file: 
    name: log/partners-meat-tms-api.log
    max-history: 90
    max-size: 100MB

jwt:
  header: Authorization
  secretKey: jungdaejang-pransportation-meat-jwt-secret-key
  refreshKey: jungdaejang-pransportation-meat-jwt-refresh-key
  dataKey: userId
  token-validation-in-seconds: 86400

server:
  port: 8030